  name: FloatingTextParticles
  main: xenialdan\FloatingTextParticles\Loader
  version: 0.0.0
  api: ['3.0.0-ALPHA9']
  load: POSTWORLD
  authors: [XenialDan]
  prefix: "FloatingTextParticles by XenialDan"